---
title: "402_final_proj_eda"
author: "Harrison DiStefano"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r load data}
# Only works in rstudio
file_directory <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(file_directory)
hotels <- read.csv("../raw_data/hotel_bookings.csv")
head(hotels)
summary(hotels)
```

```{r correlation plot}
library(dplyr)
library(reshape2)
library(ggplot2)

# Get data into a useable shape
hotels_numeric <- hotels %>% 
                    select(where(is.numeric)) %>%
                    select(-children)  # Children is ordinal

#arrival date of year, week number, and month are not numerical predictors
hotels_numeric1 <- hotels_numeric[,c(-3,-4,-5)]

corr_matrix <- cor(hotels_numeric1)
corr_matrix[upper.tri(corr_matrix)] <- NA  # Get only upper triangle of heatmap
melted_corr <- melt(corr_matrix, na.rm = TRUE)

# Plot
heatmap <- ggplot(data = melted_corr, aes(x=Var1, y=Var2, fill=value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                       midpoint = 0, limit = c(-1,1), space = "Lab",
                       name = "Pearson\nCorrelation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = .25,
                                   size = 10, hjust = 1)) + 
  coord_fixed()

heatmap +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank()
  )
```

```{r required car spaces histogram}
# Histogram of required car parking spaces
ggplot(data = hotels, aes(x=required_car_parking_spaces, group=is_canceled, fill=is_canceled)) +
  geom_histogram(position = "dodge", binwidth = 0.5) +
  theme(legend.position = "none")
```

```{r required car spaces proportion}
# Percent of reservations canceled by required car parking spaces
ggplot(data = hotels, aes(x=required_car_parking_spaces, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  labs(fill = "is_canceled")
```

```{r agent}
# TRUE if an agent was used for the booking, FALSE otherwise
hotels$used_agent <- hotels$agent != "NULL"

# Used agent by cancellation rate
ggplot(data = hotels, aes(x=used_agent, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  labs(fill = "is_canceled")

# Could possibly compare agents that have a large number of bookings
ggplot(data = hotels, aes(x=agent)) +
  geom_histogram(stat = "count")
```

```{r deposit type}
# Deposit type by cancellation rate

# merge non refund and refundable into Deposit
hotels$deposit_type1 <- ifelse(hotels$deposit_type == "Non Refund","Deposit", ifelse(hotels$deposit_type == "Refundable", "Deposit", "No Deposit"))

# deposit vs no deposit
ggplot(data = hotels, aes(x=deposit_type1, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))

# generate a plot when there is deposit (non refund vs refundable)
a <- hotels %>% group_by(deposit_type) %>% summarise(is_canceled = is_canceled)
refund <- subset(a,!(a$deposit_type == "No Deposit"))
names(refund)[names(refund) == "deposit_type"] <- "deposit_refunds"
ggplot(data = refund, aes(x=deposit_refunds, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))

  
```


```{r international booking}
# Assuming the two hotels are in Portugal
hotels$international_booking <- hotels$country != "PRT"

ggplot(data = hotels, aes(x=international_booking, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  labs(fill = "is_canceled")
```

## Added some stuff: 
```{r customer type}
ggplot(data = hotels, aes(x=customer_type, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))
```
```{r Repeated Guest}
ggplot(data = hotels, aes(x=is_repeated_guest, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))
```
```{r Assigned Room Type}
#remove observations for P room type and L room type since there are only 13 observations for both 
hotels <- hotels[-c(which(hotels$assigned_room_type=="P")),]
hotels <- hotels[-c(which(hotels$assigned_room_type=="L")),]

ggplot(data = hotels, aes(x=assigned_room_type, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))
```



```{r ADR}
#remove 2 outliers (one irregularly high, the other negative)
max <- which(hotels$adr == max(hotels$adr))
min <- which(hotels$adr == min(hotels$adr))
hotels <- hotels[c(-max,-min),]

#generate a plot
ggplot(hotels, aes(x=adr)) + geom_histogram(binwidth=5)
```
```{r groups by the number of adults, children, and babies into single, couple, friends, a family, and familes}
#replace NA to 0 for the children variable
hotels$children[is.na(hotels$children)]<-0

#remove observations when adults is 0 (total 391 observations)
hotels <- hotels[-c(which(hotels$adults == 0)),]

hotels$group <- "NA"
hotels[c(which(hotels$adults ==1&hotels$babies==0&hotels$children==0)),36] <- "single"
hotels[c(which(hotels$adults ==2&hotels$babies==0&hotels$children==0)),36] <- "couple"
hotels[c(which(hotels$adults >=3&hotels$babies==0&hotels$children==0)),36] <- "friends"
hotels[c(which(hotels$adults >=3&hotels$babies!=0|hotels$adults >=3&hotels$children!=0)),36] <- "families"
hotels[c(which(hotels$adults <=2&hotels$babies!=0|hotels$adults <=2&hotels$children!=0)),36] <- "a family"

#create a gr df checking the #
gr <- hotels %>%  group_by(adults) %>% summarise(babies = babies, children = children)
x <- c(rep(0,118984))
gr1 <- aggregate(x ~ adults + babies + children, data = gr, FUN = length)
#single # = gr1$x[c(1)]
#couple # = gr1$x[c(2)]
#friends # = sum(gr1$x[c(3:13)])
#a family # = sum(gr1$x[c(14:15,18:22,25,26,28:30,32:36)])
#families # = sum(gr1$x[c(16,17,23,24,27,31)])

#generate a plot
ggplot(data = hotels, aes(x=group, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))

#it doesn't look very helpful.
```
```{r groups by the number of people}
hotels$number_of_people <- rowSums(hotels[,10:12])

#There are 17 observations that have more than 5 people on one reservation. Therefore, we will merge the observations that have more than 5.
hotels$number_of_people[c(which(hotels$number_of_people >= 6))] <- "6+"

#generate a plot
ggplot(data = hotels, aes(x=number_of_people, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))

```
```{r groups by adults vs adults + children vs adults + babies vs adults + babies + children}

hotels$family_combo[c(which(hotels$children==0 & hotels$babies==0))] <- "Adults only"
hotels$family_combo[c(which(hotels$children!=0 & hotels$babies==0))] <- "Adults and Children"
hotels$family_combo[c(which(hotels$children==0 & hotels$babies!=0))] <- "Adults and Babies"
hotels$family_combo[c(which(hotels$children!=0 & hotels$babies!=0))] <- "Adults, Children, and Babies"

#generate a plot
ggplot(data = hotels, aes(x=family_combo, group=is_canceled, fill=factor(is_canceled))) +
  geom_bar(position = "fill") +
  ylab("proportion") +
  scale_fill_discrete(name = "Booking Status", labels = c("Not Cancelled", "Cancelled"))

```


# Cross-Correlations: 

```{r}
devtools::install_github("laresbernardo/lares")
library(lares) # colinearity analysis
options("lares.font" = FALSE)
hotels$is_canceled <- as.factor(hotels$is_canceled)
corr_cross(hotels_numeric, 
           max_pvalue = 0.05,
           top = 10, 
           rm.na = TRUE)

corr_var(hotels_numeric, 
         is_canceled, 
         top = 5)
```


# Feature Selection: 

```{r}
library(randomForest)
library(randomForestExplainer)
hotels <- na.omit(hotels)

hotels.n <- hotels %>% mutate_if(is.character, is.factor)
set.seed(1) # for reproducibility 
train <- sample(1:nrow(hotels.n), nrow(hotels.n)*.7) # doing a 70/30 split on the data
train.dt <- hotels.n[train,]
test.dt <- hotels.n[-train,]

rf.dt <- randomForest(is_canceled~., data = train.dt, mtry = 6, importance = TRUE, ntrees = 500, na.action = na.omit)

# importance(rf.dt)
varImpPlot(rf.dt)
# Mean Decrease in Gini is the average (mean) of a variable’s total decrease in node impurity, weighted by the proportion of samples reaching that node in each individual decision tree in the random forest. 
# A higher Mean Decrease in Gini indicates higher variable importance.

pred <- predict(rf.dt, test.dt, type = "response")
table(pred, test.dt$is_canceled)
mean(pred != test.dt$is_canceled) # test error rate 
```
