---
title: "logistic_model"
author: "Jeremy Weidner"
date: "December 1, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notebook to begin fitting models on hotel data

```{r cars}
library(effects)

# install.packages("effects")

hotels <- read.csv("../raw_data/hotel_bookings.csv")
head(hotels)
summary(hotels)
```



```{r}

model_1 <- glm(is_canceled ~ lead_time + arrival_date_month + adults + children + babies + country + previous_cancellations + hotel + adr, family = binomial(), data = hotels)

# taking out country and children because they're not significant initially
model_2 <- glm(is_canceled ~ lead_time*hotel + arrival_date_month + adults +  babies + previous_cancellations + adr, family = binomial(), data = hotels)
summary(model_2)
anova(model_2)

```




# odds ratio

```{r}


round(exp(cbind(Estimate=coef(model_2), confint(model_2))),2)



```

# plot interaction effect

```{r}
# plot(allEffects(model_2, ask = FALSE))

plot(allEffects(model_2), ask=FALSE, main = "Interaction Effect: ")


```







# mmp plot
```{r}

library(car)
mmp(model_2)

```



# pearson chi square
```{r}


print(paste(“Pearson’s X^2=\“, round(sum(residuals(model_2, type=“pearson”)^2),3)))




```



```{r}

```

































































































































































































































































